This is makeindex, version 2.15 [TeX Live 2015] (kpathsea + Thai support).
Scanning style file /Users/mat/ownCloud/Uni/U_DB-Problemseminar/Ausarbeitung/.texpadtmp/main.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file /Users/mat/ownCloud/Uni/U_DB-Problemseminar/Ausarbeitung/.texpadtmp/main.acn....done (4 entries accepted, 0 rejected).
Sorting entries....done (9 comparisons).
Generating output file /Users/mat/ownCloud/Uni/U_DB-Problemseminar/Ausarbeitung/.texpadtmp/main.acr....done (9 lines written, 0 warnings).
Output written in /Users/mat/ownCloud/Uni/U_DB-Problemseminar/Ausarbeitung/.texpadtmp/main.acr.
Transcript written in /Users/mat/ownCloud/Uni/U_DB-Problemseminar/Ausarbeitung/.texpadtmp/main.alg.
